{% set version = "305" %}

package:
  name: pywin32
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: a6d7a5c5578ad0bbb4a8f9cf6ff277612dab5c21a614ea243a5bf72882f4cbca

build:
  number: 2
  script:
    - |                                                                                          
      @echo on                                                                                   
      set "STDLIB_DIR=%PREFIX%\Lib;%PREFIX%;%LIBRARY_BIN%"                                       
      {{ PYTHON }} setup.py -q install --record=record.txt --skip-verstamp                       
      echo "sleeping for 15"                                                                     
      {{ PYTHON }} -c "import time; time.sleep(15)"                                              
      echo "Copying over stray DLLS"                                                             
      if %ERRORLEVEL% neq 0 exit 1                                                               
      dir %PREFIX%\Lib\site-packages\win32\py*.dll                                               
      copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %PREFIX%\Lib\site-packages\win32\   
      dir %PREFIX%\Lib\site-packages\win32\py*.dll                                               
      if %ERRORLEVEL% neq 0 exit 1                                                               
      dir %LIBRARY_BIN%\py*.dll                                                                  
      copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%\                      
      if %ERRORLEVEL% neq 0 exit 1                                                               
      dir %LIBRARY_BIN%\py*.dll                                                                  
      if %ERRORLEVEL% neq 0 exit 1                                                               
    - echo "noop"


requirements:
  build:                         
    - {{ compiler("cxx") }}      
  host:
    - python
    - pip                        
  run:
    - python

test:
  requires:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  dev_url: https://github.com/mhammond/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
