{% set version = "302" %}

package:
  name: pywin32
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: 47fd53c0561ff3019043e86880597aacbd736910d8add485117d8ad055441927
  patches:
    - disable_exchange_modules.patch
    - 0003-remove-PATH-pth-hack.patch

build:
  number: 2
  script:
    - @echo on
    - {{ PYTHON }} setup.py -q install --record=record.txt --skip-verstamp
    - if %ERRORLEVEL% neq 0 exit 1
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %PREFIX%\Lib\site-packages\win32\
    - if %ERRORLEVEL% neq 0 exit 1
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%\
    - if %ERRORLEVEL% neq 0 exit 1
  skip: true  # [not win]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  dev_url: https://github.com/mhammond/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
