{% set version = "224" %}

package:
  name: pywin32
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: 172c5618d22cf8e9bca7bc01699c4bd94d4b03c926a6da125d5fe9b8eaa2837b

build:
  number: 1000
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%
  skip: True  # [not win or py27]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF
  summary: Python extensions for Windows

extra:
  recipe-maintainers:
    - nicoddemus
    - carlodri
