{% set name = "pywin32" %}
{% set version = "221" %}
{% set hash_type = "sha256" %}
{% set hash = "5faa048471cdd4eefcde9dbada0782fd95868d7cce2704ee06b75ca40849e08f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://downloads.sourceforge.net/project/{{ name }}/{{ name }}/Build {{ version }}/{{ name }}-{{ version }}.zip
  {{ hash_type }}: {{ hash }}
  patches:
    - 0001-scintilla_makefiles.patch
    - 0002-ucrt-compatibility-fixes.patch
    - 0003-ucrt-compatibility-fixes-shell.patch
    - 0004-fix-mapi-compile-errors.patch
    - 0005-remove-JOB_OBJECT_RESERVED_LIMIT_VALID_FLAGS.patch

build:
  number: 0
  script: 
  skip: True  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
  run:
    - python

about:
  home: https://sourceforge.net/projects/pywin32
  license: PSF
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  doc_url: https://pypi.python.org/pypi/pywin32
  doc_source_url: https://sourceforge.net/projects/pywin32/

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
