{% set version = "225" %}

package:
  name: pywin32
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: b8bd621f91dfec2e836695aa333231dcf97d826ffd06e9bc0bf3a0c6265a7f6f
  patches:
    - disable_exchange_modules.patch

build:
  number: 0
  script:
    - "{{ PYTHON }} setup.py -q install --record=record.txt"
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%
  skip: True  # [not win or py27]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows

extra:
  recipe-maintainers:
    - nicoddemus
    - carlodri
