{% set version = "303" %}

package:
  name: pywin32
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: bc3980d80e351333cc5566c7847d8f179828f2678d8539eed0e52d39ea0c3970
  patches:
    - 0003-remove-PATH-pth-hack.patch
    # https://github.com/mhammond/pywin32/commit/9fbc2ed3c0d69aca2475975a599cc316016599d3
    # - fix-formatting.patch
    # HACK: Avoid https://bugs.python.org/issue42009
    # - ensure-PythonService-mc-before-cpp.patch
    # - add-verbosity-to-setup-py.patch

build:
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - {{ compiler("c") }}
    - m2-patch  # [win]
    - m2-gcc-libs  # [win]
    - patch  # [not win]
  host:
    - python
    - pip
    - setuptools
  run:
    - python

about:
  home: https://github.com/mhammond/pywin32
  # For more detail on the license look at the following issue
  # https://github.com/mhammond/pywin32/issues/1127
  license: HPND AND BSD-3-Clause AND LGPL-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  dev_url: https://github.com/mhammond/pywin32
  doc_url: https://mhammond.github.io/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
