{% set name = "pywin32" %}
{% set version = "220" %}
{% set hash_type = "sha1" %}
{% set hash = "88ba6a31c077a9e1b49b59dc215ddadc6aa5e3d6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://downloads.sourceforge.net/project/{{ name }}/{{ name }}/Build {{ version }}/{{ name }}-{{ version }}.zip
  {{ hash_type }}: {{ hash }}

build:
  number: 1
  script: 
    - python setup.py install --record=record.txt  # [not py3k]
    - python setup3.py install --record=record.txt  # [py3k]
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %PREFIX%

  skip: True  # [not win]

requirements:
  build:
    - python 
  run:
    - python

test:
  commands:
    - dir %PREFIX%\pythoncom%CONDA_PY%.dll
    - dir %PREFIX%\pywintypes%CONDA_PY%.dll

about:
  home: https://sourceforge.net/projects/pywin32
  license: PSF
  summary: Python extensions for Windows

extra:
  recipe-maintainers:
    - nicoddemus
