{% set name = "pywin32" %}
{% set version = "305" %}
{% set build = "0" %}
{% set checksum = "a6d7a5c5578ad0bbb4a8f9cf6ff277612dab5c21a614ea243a5bf72882f4cbca" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: {{ checksum }}
  patches:
    - patches/0001-remove-PATH-pth-hack.patch
    - patches/0002-disable_exchange_modules.patch
    - patches/0003-MSVC_dirs_setup.patch
    - patches/0004-MSVC_dirs_setup_fix.patch

build:
  number: {{ build }}
  skip: True  # [not win]

requirements:
  build:
    - {{ compiler("c") }}
    - m2-patch  # [win]
    - m2-gcc-libs  # [win]
    - patch  # [not win]
  host:
    - python
    - pip
    - setuptools
  run:
    - python

about:
  home: https://github.com/mhammond/pywin32
  # For more detail on the license look at the following issue
  # https://github.com/mhammond/pywin32/issues/1127
  license: HPND AND BSD-3-Clause AND LGPL-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  dev_url: https://github.com/mhammond/pywin32
  doc_url: https://mhammond.github.io/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
