{% set name = "pywin32" %}
{% set version = "223" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mhammond/{{ name }}/archive/b{{ version }}.tar.gz
  sha256: c8be831cb0fc11badf27b6edc0da08984322452e5c98ac84aa158cc89f6d0837

build:
  number: 0
  script:
    - "{{ PYTHON }} setup.py install --record=record.txt"  # [not py3k]
    - "{{ PYTHON }} setup3.py install --record=record.txt"  # [py3k]
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%

  skip: True  # [not win and py27]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF
  summary: Python extensions for Windows

extra:
  recipe-maintainers:
    - nicoddemus
    - carlodri
