{% set name = "pywin32" %}
{% set version = "308" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: 8aa09d39739764bec2378cfbd45940264c8b7f5a24caa17f04a01f7b750799ce
  patches:
    - patches/0001-remove-PATH-pth-hack.patch

build:
  number: 0
  skip: True  # [not win]
  missing_dso_whitelist:
    - $RPATH/axscript.pyd
    - $RPATH/win32ui.pyd
    - $RPATH/win32uiole.pyd
  ignore_run_exports:
    - vs2015_runtime

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - m2-patch
    - m2-gcc-libs
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  files:
    - test_win32gui.py
  requires:
    - pip
  vars:
    - LIBRARY_BIN=%PREFIX%\Library\bin
    - pip check
    - python run_test.py
    - python test_win32gui.py

about:
  home: https://github.com/mhammond/pywin32
  # For more detail on the license look at the following issue
  # https://github.com/mhammond/pywin32/issues/1127
  license: HPND AND BSD-3-Clause AND LGPL-2.1-or-later AND MIT
  license_file:
    - Pythonwin/License.txt  # BSD-3-CLause
    - Pythonwin/Scintilla/License.txt  # MIT
    - win32/License.txt  # BSD-3-CLause
    - com/License.txt  # BSD-3-CLause
    - com/win32comext/mapi/src/mapi_stub_library/LICENSE  # MIT
    - adodbapi/license.txt  # LGPL-2.1-or-later  summary: Python extensions for Windows
  description: A set of extension modules that provides access to many of the Windows API functions.
  summary: A set of extension modules that provides access to many of the Windows API functions.
  dev_url: https://github.com/mhammond/pywin32
  doc_url: https://mhammond.github.io/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
  # Explicitly skip license linting because of the license complexity
  skip-lints:
    - missing_license_family