{% set name = "pywin32" %}
{% set version = "226" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mhammond/{{ name }}/archive/b{{ version }}.tar.gz
  sha256: 172c5618d22cf8e9bca7bc01699c4bd94d4b03c926a6da125d5fe9b8eaa2837b

build:
  number: 0
  script:
    - "{{ PYTHON }} setup.py install --record=record.txt"  # [not py3k]
    - "{{ PYTHON }} setup3.py install --record=record.txt"  # [py3k]
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%

  skip: True  # [not win or py27]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF
  summary: Python extensions for Windows

extra:
  recipe-maintainers:
    - nicoddemus
    - carlodri
