{% set name = "pywin32" %}
{% set version = "221" %}
{% set hash_type = "sha256" %}
{% set hash = "5faa048471cdd4eefcde9dbada0782fd95868d7cce2704ee06b75ca40849e08f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://github.com/mhammond/{{ name }}/archive/b{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script:
    - python setup.py install --record=record.txt  # [not py3k]
    - python setup3.py install --record=record.txt  # [py3k]
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%

  skip: True  # [not win]

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - if not exist %LIBRARY_BIN%\pythoncom%CONDA_PY%.dll exit 1
    - if not exist %LIBRARY_BIN%\pywintypes%CONDA_PY%.dll exit 1

about:
  home: https://github.com/mhammond/pywin32
  license: PSF
  summary: Python extensions for Windows

extra:
  recipe-maintainers:
    - nicoddemus
