travis:
  secure:
    BINSTAR_TOKEN: qX9cAgW3Dk5aE4e3Z4rrxY4Zl7aVoamAvZozQGACMjIXmB2ON2dR6+kPU7PP8F5n6Oi/SWfVrJ5o6hzeT8DI9B5G/8ZsbbpkfcSXhprcu5JURjdA3IEgOoy7Tqbp9/d/7QB7ZPFq/MkIBNADAvAXadujXVZnczWWslif5EG/iK/UmGtStHlCSAqGnWDslG/BwLxvHeKDhg38X2WycpGIkp7baT+BkzypNwGZMDP5YZ9gieHyv+Xk7CroUmq878KVQJFkc/+S/TXm498GHm96krZSeL5z+00H/CcD5O6MnvFDyMppF1p2MbAvrqdz44e74Y0s+LRAuebJqUX0raR4PD63yZ0l+NQosvZWhjxDpbxiE8izqV60PqVmkdthvHJeY+fFXfROlz9JxrRjKz3O92rrJpyOOZJUzkbw9riJlXdgoYbIvd8r3B363ae549DyuOU1p50y2xhx+rx3DLunpg+/lmgJ0V9cF2/M+UTr6xCklgWRbYh1+MynxKuKFxceoVA5+5Kwj4hhQp2io3GkCd0LwPUC5ZkMq/4o6v1sjMsc+CCBJPJ8IlyfAchVH0KGTeUbij8sfEHf3+DF1YtXSvQK4vdeWLbzC96PEgUju3VM69fB512kGhOP01yTMZOwL1TbS+LmW065aE+nZGWzmDQDl1uFAjeQMWVX2S8fIXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
