travis:
  secure:
    BINSTAR_TOKEN: h8z96k2hGpWJYcEOBoK5phslIL+NEHuIa5h3tDKET9Wr1gYHPzxOa/RRCQi1oycyvb/k1/7drzjd8I+SuiLA3GAu/v4Hqsjfr26JO1nwL2LgBO4MFnRo4M8KgSo5g9gEL3uF3bZFaiSxQNtHNXTlJyYk8UmvkrgzEX8AGfCxASNjxDV/BrDFKjvH2Id7gGTdgUaMEAmj8TKbYn7Y0i0gswzbQdCWvP9nTn83BsjD0SrxeAA8xzdaaHoJpK8pg3gii4ZYbgjGSBcOxfcwtw3jrsKobA9SNphaideMjCn8B0wGwodH9DLg+Pd5UycMc4EPmy+zpLnisgufZspFZh2IA6KUXV5E5szMKIkdCJfJEKKXhVWAzyJJxxl5DNrb3h80STnGD3q+GO9q4SCeQKbYOZTrpLMDKsBLguqi8Y8UJ7ymSrP4Smkebkar2TBxOgScti/kk9IcXk2NL6Gcvsj9EtG0lDL7kWtPo5P2SArgPp+yYVQaiOLjBtH90WU2LF33JeNwim/i2a4NQx072vF0KNB+7wII9MK4dBs0TYkVE7JmWvUISqGLB/4NIzTMpJBeJ2qbdF6g6IVQ5LQezf/PNvR8W+NxBFTwLCtYxzdsrrG0RZjeDHVY6ZaTZRgDBSztr0CGm7vw+SFhqZYwfVnMU7QmLh6aqEX2q+wPD0Vi8Ak=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
